{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.11.11","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"},"kaggle":{"accelerator":"none","dataSources":[],"dockerImageVersionId":31040,"isInternetEnabled":false,"language":"python","sourceType":"notebook","isGpuEnabled":false}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"# This Python 3 environment comes with many helpful analytics libraries installed\n# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python\n# For example, here's several helpful packages to load\n\nimport numpy as np # linear algebra\nimport pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)\n\n# Input data files are available in the read-only \"../input/\" directory\n# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory\n\nimport os\nfor dirname, _, filenames in os.walk('/kaggle/input'):\n    for filename in filenames:\n        print(os.path.join(dirname, filename))\n\n# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using \"Save & Run All\" \n# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","trusted":true,"execution":{"iopub.status.busy":"2025-07-04T06:00:46.584215Z","iopub.execute_input":"2025-07-04T06:00:46.584578Z","iopub.status.idle":"2025-07-04T06:00:46.591709Z","shell.execute_reply.started":"2025-07-04T06:00:46.584551Z","shell.execute_reply":"2025-07-04T06:00:46.590767Z"}},"outputs":[],"execution_count":5},{"cell_type":"code","source":"!pip install --upgrade --quiet keras-cv\n!pip install --upgrade --quiet keras","metadata":{"trusted":true,"execution":{"iopub.status.busy":"2025-07-04T06:00:46.598799Z","iopub.execute_input":"2025-07-04T06:00:46.599105Z","iopub.status.idle":"2025-07-04T06:17:30.491708Z","shell.execute_reply.started":"2025-07-04T06:00:46.599081Z","shell.execute_reply":"2025-07-04T06:17:30.490298Z"}},"outputs":[{"name":"stdout","text":"\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6d42cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/keras-cv/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6d68a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/keras-cv/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6d6b0d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/keras-cv/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6d51c90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/keras-cv/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6d67cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/keras-cv/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c8bbd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/protobuf/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c8bfd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/protobuf/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c90a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/protobuf/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c91550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/protobuf/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c92010>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/protobuf/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c92450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/tensorflow-metadata/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c93150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/tensorflow-metadata/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c93b90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/tensorflow-metadata/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c9c650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/tensorflow-metadata/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c9d350>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/tensorflow-metadata/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c53690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/tensorflow-datasets/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c77e10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/tensorflow-datasets/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c47710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/tensorflow-datasets/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c403d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/tensorflow-datasets/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7c11d6c41ad0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/tensorflow-datasets/\u001b[0m\u001b[33m\n\u001b[0m\u001b[31mERROR: Cannot install tensorflow-datasets==4.9.8 and tensorflow-metadata==1.17.0 because these package versions have conflicting dependencies.\u001b[0m\u001b[31m\n\u001b[0m\u001b[31mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts\u001b[0m\u001b[31m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7d1b321b1c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/keras/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7d1b320c5f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/keras/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7d1b320c0150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/keras/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7d1b3203de10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/keras/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7d1b32099e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/keras/\u001b[0m\u001b[33m\n\u001b[0m","output_type":"stream"}],"execution_count":6},{"cell_type":"code","source":"import os\n\nos.environ[\"KERAS_BACKEND\"] = \"jax\"\n\nimport keras\nimport keras_cv\nimport numpy as np\nimport tensorflow_datasets as tfds\nimport matplotlib\n\nataset = tfds.load(\n    \"cats_vs_dogs\", split=\"train\", as_supervised=True, batch_size=128\n)\n\n# Resize images to a common size.\nresize = keras_cv.layers.Resizing(224, 224, crop_to_aspect_ratio=True)\ndataset = dataset.map(lambda x, y: (resize(x), y))\n\n# Split off some valication data\nvalidation_size = int(dataset.cardinality().numpy() * 0.1)\nval_data = dataset.take(validation_size).shuffle(100)\ntrain_data = dataset.skip(validation_size).shuffle(100)","metadata":{"trusted":true,"_kg_hide-input":true,"execution":{"iopub.status.busy":"2025-07-04T06:17:30.493527Z","iopub.execute_input":"2025-07-04T06:17:30.494120Z"}},"outputs":[{"name":"stdout","text":"Downloading and preparing dataset Unknown size (download: Unknown size, generated: Unknown size, total: Unknown size) to /root/tensorflow_datasets/cats_vs_dogs/4.0.1...\n","output_type":"stream"},{"output_type":"display_data","data":{"text/plain":"Dl Completed...: 0 url [00:00, ? url/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"cd6c26ddc7c44004aeee1cf01b880481"}},"metadata":{}},{"output_type":"display_data","data":{"text/plain":"Dl Size...: 0 MiB [00:00, ? MiB/s]","application/vnd.jupyter.widget-view+json":{"version_major":2,"version_minor":0,"model_id":"278424ff00d94294ad13338ca7afc15d"}},"metadata":{}}],"execution_count":null},{"cell_type":"code","source":"dataset = tfds.load(\n    \"cats_vs_dogs\", split=\"train\", as_supervised=True, batch_size=128\n)\n\n# Resize images to a common size.\nresize = keras_cv.layers.Resizing(224, 224, crop_to_aspect_ratio=True)\ndataset = dataset.map(lambda x, y: (resize(x), y))\n\n# Split off some valication data\nvalidation_size = int(dataset.cardinality().numpy() * 0.1)\nval_data = dataset.take(validation_size).shuffle(100)\ntrain_data = dataset.skip(validation_size).shuffle(100)","metadata":{"trusted":true},"outputs":[],"execution_count":null}]}